language: node_js
addons:
  code_climate:
    repo_token: 2be384b96f2cd2d2d171991d284c362751e0a0836b6ba1a9e49dc798b309a725
node_js:
  - "5.0"
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/all/lcov.info
  - grunt coveralls
